### PR TITLE
dapps.asciidoc heading style normalization and standardization

### PR DESCRIPTION
**Pull request by nuke-web3**
hope this is what you were looking for in #446 for the dapps.asciidoc file.

Let me know what else I can do for this guy - otherwise I will tackle another chapter in a similar fashion.

### CODE REVIEW

**Comment by nuke-web3** [comment]
Also:
multiple level two (==) headings in this doc - should we consider shifting all to higher level beyond title?

**Comment by abhiShandy** [comment]
Only the chapter title should have 2nd level heading. Sections and sub-sections will have 3rd and 4th level headings respectively.

**Comment by aantonop** [comment]
Yes, only the chapter/section should be level 2, everything else should be level 3 and below. 

Also, once you have spelled out an acronym in one heading I think we can keep it as an acronym in subsequent headings (eg. DApp from the second heading forwards). 

Nice work!

**Comment by nuke-web3** [comment]
Thanks @aantonop ! I am about to correct the levels and acronyms - might be a good idea to update your issue to reflect that for others contributing

**Comment by Elenore23** [comment]
> hope this is what you were looking for in #446 for the dapps.asciidoc file.
> 
> Let me know what else I can do for this guy - otherwise I will tackle another chapter in a similar fashion.

**Pull request merged**
