### PR TITLE
Governance chapter

### LINKED ISSUE #336: Blockchain Governance from a Developer point of view
Through this issue I intend to highlight the importance that it can have for a developer to know what or who governs the evolution of the Ethereum protocol.

### PR DESCRIPTION
**Pull request by lrettig**
First draft of governance chapter. Closes #336. Still a few lingering to do items, need to clean up references a bit.

### CODE REVIEW

**Comment by pyskell** [comment]
Haven't read through it all yet but: 

- [ ] I think you may be giving too many examples / explanations of things (ex. the Coordination problems section)
- [ ] I'd put the aim/purpose for governance ahead of Governance in general
- [ ] Terminology might be better in the glossary, and introducing people to terminology might work better in a story structure (introduce and explain each term as it's needed)
- [ ] I'd also maybe suggest doing an explanation of governance only in the context of blockchain, or using blockchain as an example (though I'm not sold on this thought). It just might cut down on the total amount of reading
- [ ] I'd also summarize the positives and negatives of governance, maybe in a table early on (and probably structure some of the discussion around this)

Anyways just ideas, you've obviously thought this through a lot

**Comment by lrettig** [comment]
Thanks, this is excellent feedback. I welcome PRs as well as suggestions :)

**Comment by lrettig** [comment]
Thanks for the fantastic feedback @DigitalFuturesBUILD. Will take this into consideration. Given yesterday's deadline for drafts making it into the first edition, I'm going to wait to hear from @aantonop before doing the heavy editing -- if this stands a serious chance of making it into the first edition, I'm happy to edit heavily. If not we have plenty of time.

**Comment by aantonop** [comment]
Please proceed with editing. We have until Monday or Tuesday.

**Pull request merged**
