### PR TITLE
Chapter 6: Fixes missing closing tag for u1 var

### PR DESCRIPTION
**Pull request by dbachko**
Before:
screen shot 2019-01-16 at 12 39 00 am

After:
Screen Shot 2020-01-18 at 8 14 36 PM

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
I suggest that we should keep the symbol *, to be consistent with other parts in the book.

But this PR makes a great point: there is an unexpected underscore in the formula.

**Review by 0xmountaintop — CHANGES_REQUESTED** [review]
I suggest that we should keep the symbol *, to be consistent with other parts in the book. But this PR makes a great point: there is an unexpected underscore in the formula.

**Comment by dbachko** [comment]
@HAOYUatHZ fixed

**Comment by ChrisLinn** [comment]
> @HAOYUatHZ fixed

@dbachko would be better if also updating the pic in the PR description

**Comment by 0xmountaintop** [comment]
> @HAOYUatHZ fixed

@dbachko would be better if also updating the pic in the PR description

**Review by 0xmountaintop — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
LGTM

**Comment by wbnns** [comment]
@dbachko @HAOYUatHZ Thank you.

**Pull request merged**
