### PR TITLE
style: lint contract codes in "code/Solidity"

### PR DESCRIPTION
**Pull request by 0xmountaintop**
1. function order should be: constructor -> external -> public -> internal -> private
2. Contracts and libraries should be named using the CapWords style. 
3. 'function () ' -> 'receive()' in solidity 0.6
4. constructor visibility should be explicit
5. The `address` type was split into `address` and `address payable`
6.  It is now necessary to explicitly convert values of contract type to addresses before using an address member. Example: if c is a contract, change c.transfer(...) to address(c).transfer(...), and c.balance to address(c).balance.

### CODE REVIEW

**Comment by wbnns** [comment]
@HAOYUatHZ 

Heya! Not sure if you'd still like to pursue this PR -- if you do, could you please rebase and resolve merge conflicts?

**Comment by 0xmountaintop** [comment]
> @HAOYUatHZ
> 
> Heya! Not sure if you'd still like to pursue this PR -- if you do, could you please rebase and resolve merge conflicts?

No problem. Will do!

**Comment by wbnns** [comment]
Thank you, sir!

**Comment by 0xmountaintop** [comment]
Hi! @wbnns I have updated the code and use 0.6.4 specified in https://github.com/ethereumbook/ethereumbook/pull/962.

You may want to take a look again.

**Comment by wbnns** [comment]
Ok, great!

**Pull request merged**
