### PR TITLE
DAO fork history and differences between Ethereum and Ethereum Classic

### PR DESCRIPTION
**Pull request by pyskell**
This continues PR #479 as GitHub seems to not be allowing me to re-open it after merge.

TODO: 
- [x] Turn DAO timeline into a story structure (possibly; may function well as a raw timeline)
- [x] Organize DAO timeline references
- [x] Add other Ethereum-based forks (both blockchain and software-based forks)
- [ ] Expand on other Ethereum-based forks if developers/members of these blockchains want

Pinging @chanan-sack 😄

### CODE REVIEW

**Comment by pyskell** [comment]
I'd also like to get input on whether or not arguments for/against The DAO Hardfork are appropriate for this book since it can stray into opinion territory.

**Comment by aantonop** [comment]
I think a factual, unemotional, and balanced presentation of the key points
as bullet list is sufficient but also relevant and necessary.

**Comment by aantonop** [comment]
Would you consider this ready to merge?

**Comment by pyskell** [comment]
It will be on Monday. I just want to read it over and proof it once more.
I'll ping you once I do.

**Comment by pyskell** [comment]
Done with my proofing of the draft. Feel free to merge.

Pinging @chanan-sack & @aantonop

**Pull request merged**
