### PR TITLE
added testnet faucets

### PR DESCRIPTION
**Pull request by ChristopherGondek**
I added some information about test ether faucets. I reasoned why there are faucets and which faucets exist. This list of faucets can, however, never be complete as there may be many different private faucets. I guess we can only link to the most prominent ones.

### CODE REVIEW

**Comment by RichHorrocks** [comment]
Hi there. Quick comment: I'm struggling to see the reasoning stating that faucets offer a level of protection against abuse and attacks. Can you add a few clarifying details?

**Comment by ChristopherGondek** [comment]
Hi. Sure. This is the main reason why faucets only give very little ether. Without that restriction, anyone could request lots of ether and constantly sending transactions. That would put the test network under stress and therefore inhibit developers. Also, the blockchain would grow in size unnecessarily. After ethers are distributed, it will be very hard to see which transactions are malicious and which are not. On the other hand, for normal DApp development, few ethers are usually sufficient.

**Comment by RichHorrocks** [comment]
Okay, that makes sense - I hadn't considered that. However, other than the financial disincentive, there's nothing to stop anyone actually mining a PoW testnet, so faucets wouldn't stop someone with some cash to spare from acting maliciously (as was the case with Morden and the first iteration of Ropsten?). Which is then presumably why the PoA testnets were created. (Just thinking out loud... )

**Comment by ChristopherGondek** [comment]
Yes, that is true. However, it requires some resources than to spam a PoW testnet. PoA networks are also highly beneficial when developing DApps. They are more reliable than PoW test networks. They are not as quick as single node networks, but they come with e.g. public blockchain explorers and so on. I personally like to develop DApps on PoA networks in later stages. E.g. to present. This is getting off-topic, however.

**Pull request merged**
